version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - olik-mongo-db:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

volumes:
  olik-mongo-db:
